### ISSUE TITLE
FeatureRequest: Resolve merge conflicts by using 'ours' or 'theirs'

### ISSUE THREAD

**Issue by Lacront** [saitho/semantic-release-backmerge#13]
Hey, first of all thank you for this plugin!

Would it be possible to add a extra configuration for resolving merge conflicts automatically by using
`git checkout --ours *`
`git checkout --theirs *`
before doing the merge?

Like here:
https://nitaym.github.io/ourstheirs/

Background:
I have to track my version in the package.json and package-lock.json files.
My **master** branch is used for INT and PROD deployments.
My **develop** branch is used for DEV/NEXT deployments and will be merged into **master** for INT/PROD releases.
If I have to push a hotfix to my **master** branch I would like it to backmerge it into **develop**.
Currently this throws merge conflicts because of the version difference in the package files.. thus this feature request.

In my case I can always use the files in the **master** branch in case of a merge conflict without any issues.

Thank you!

**Comment by saitho** [comment]
Yeah, lock files are a pain in the ass I know that as well. ^^
Generally speaking I'm cautious about blindly merging from ours or theirs, but I guess I can add a setting to explicitly enable that behaviour.

**Comment by hendrikhalkow** [comment]
We need this feature because we use this plugin together with the [gradle-semantic-release-plugin](https://www.npmjs.com/package/gradle-semantic-release-plugin) that writes the current version to `gradle.properties` during a release. When you create a release candidate (PR from develop to rc, backmerge to develop), then a release (PR from rc to release, backmerge to develop), the release backmerge will conflict with the rc backmerge, because of the gradle.properties that contains updated version.

As a workaround, we do our releases from our develop branch, which is not ideal, because the develop branch may contain newer code that we don't want to include in the release and which wasn't part of the release candidate.

**Comment by saitho** [comment]
Hi there! I haven't been working on my GitHub repositories lately.

The options `--theirs` and `--ours` on the `checkout` command seem to only work for individual files.
The option `-X` on the `merge` command from your current workaround seems to work nicely.

I added a new setting `mergeMode` which either be set to "ours", "theirs" or "none" (default) to specify how merge conflicts are resolved when "merge" is selected as backmerge strategy.
